# permissions for end users to edit storageconsumers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: storageconsumer-editor-role
rules:
- apiGroups:
  - ocs.openshift.io
  resources:
  - storageconsumers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ocs.openshift.io
  resources:
  - storageconsumers/status
  verbs:
  - get
